name: Bottomless Water
author: Gabriel
version: 3.3.0
description: >-
  Keeps players' liquid containers full with per-player toggles,
  whitelist/exclude lists, cooldowns, logging, and improved performance.
language: C#
game: rust
license: MIT
