name: Bottomless Water
author: Gabriel
version: 2.3.1
description: >-
  Keeps players' liquid containers full with per-player toggles,
  whitelist/exclude lists, cooldowns, logging, and improved performance.
language: C#
game: rust
license: MIT
