name: Bottomless Water
author: gjdunga
version: 1.0.0
description: Lets players place water containers that stay full (LiquidContainer): water catchers, barrels, etc. Per-player toggle, permission-based, admin controls.
language: C#
game: rust
license: MIT
